apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongodb-database.fullname" . }}
  labels:
    {{- include "mongodb-database.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mongodb-database.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mongodb-database.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mongodb-database.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mongodb-database.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - mongod
        - --config
        - /etc/mongo/mongod.conf
        ports:
        - name: mongodb
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        env:
        {{- if .Values.auth.enabled }}
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.auth.rootUser | quote }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mongodb-database.secretName" . }}
              key: mongodb-root-password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "mongodb-database.secretName" . }}
              key: mongodb-database
        {{- end }}
        {{- with .Values.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /etc/mongo
        - name: logs
          mountPath: /var/log/mongodb
        {{- if .Values.initdb.enabled }}
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
      {{- if .Values.metrics.enabled }}
      - name: metrics
        image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
        ports:
        - name: metrics
          containerPort: {{ .Values.metrics.port }}
          protocol: TCP
        env:
        {{- if .Values.auth.enabled }}
        - name: MONGODB_URI
          value: "mongodb://{{ .Values.auth.rootUser }}:$(MONGODB_ROOT_PASSWORD)@localhost:{{ .Values.service.port }}"
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mongodb-database.secretName" . }}
              key: mongodb-root-password
        {{- else }}
        - name: MONGODB_URI
          value: "mongodb://localhost:{{ .Values.service.port }}"
        {{- end }}
        resources:
          {{- toYaml .Values.metrics.resources | nindent 12 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "mongodb-database.fullname" . }}-config
      - name: logs
        emptyDir: {}
      {{- if .Values.initdb.enabled }}
      - name: initdb
        configMap:
          name: {{ include "mongodb-database.fullname" . }}-initdb
      {{- end }}
      {{- if not .Values.persistence.enabled }}
      - name: data
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        {{- include "mongodb-database.labels" . | nindent 8 }}
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
  {{- end }}
